version: 0.3.0-{build}
os: Visual Studio 2015
environment:
  matrix:
    - nodejs_version: 8.1.4
      platform: x64
    - nodejs_version: 8.1.4
      platform: x86
    - nodejs_version: 5.10
      platform: x64
    - nodejs_version: 5.10
      platform: x86
    - nodejs_version: 4.4
      platform: x64
    - nodejs_version: 4.4
      platform: x86
  access_token:
    secure: dEViCwlC9QsVdmBzdbybivULfYql2xhNYGD5/qhN3pM1OhCjvmZx1xGLGNg5paSW
  NODE_PRE_GYP_GITHUB_TOKEN: dEViCwlC9QsVdmBzdbybivULfYql2xhNYGD5/qhN3pM1OhCjvmZx1xGLGNg5paSW

cache:
  - '%APPDATA%\npm-cache'
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule init
  - git submodule update
  # Upgrade npm
  # - npm install -g npm
  - npm install -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g node-pre-gyp 
  - npm install -g node-pre-gyp-github
  - npm install --build-from-source

build_script:
  - node-pre-gyp configure
  - node-pre-gyp build
  - node-pre-gyp package
test: off
artifacts:
  - path: .\build\stage
on_success:
  - node-pre-gyp-github publish --release